export const TEST = 'TEST_ACTION';
export const PUSHER_INSTANCE = 'PUSHER_INSTANCE';
export const PUSHER_CHANNEL = 'PUSHER_CHANNEL';
export const SET_NETWORK_STATE = 'SET_NETWORK_STATE';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SET_CURRENT_CHAT_USER = 'SET_CURRENT_CHAT_USER';
export const SET_CURRENT_CONVERSATION_ID = 'SET_CURRENT_CONVERSATION_ID';
export const FETCHED_CONVERSATION_MESSAGES = 'FETCHED_CONVERSATION_MESSAGES';
